language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install: "pip install -e ."
# command to run tests
script: cd ./testproject && python manage.py test