language: python
python:
  - "3.4"
  - "3.5"
env:
  # - DJANGO_VERSION=1.7.11
  - DJANGO_VERSION=1.8.12
  - DJANGO_VERSION=1.9.5
# command to install dependencies
install:
  - pip install -q django==$DJANGO_VERSION
  - pip install -e .
# command to run tests
script: cd ./testproject && python manage.py test